include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - build/**
    - lib/**/**.g.dart
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    sort_constructors_first: false
    always_use_package_imports: false
    one_member_abstracts: false
    flutter_style_todos: false
    avoid_returning_this: false
    require_trailing_commas: false
    sort_pub_dependencies: false
