name: musiquiz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.1
  dio: ^4.0.4
  stack_trace: ^1.11.0
  universal_html: ^2.0.9
  spotify_sdk: ^2.3.1
  models:
    path: ../models
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
