name: models
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  json_annotation: ^4.8.0
  
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
